# Generated by Django 5.2.14 on 2026-05-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Boshqaruvchi'), ('dispatcher', 'Dispecher'), ('driver', 'Haydovchi')], default='dispatcher', max_length=15),
        ),
    ]
